version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mysam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ctwdbvc0fg6c"
s3_prefix = "mysam"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
